variables:
    # The host for the test SGame instance
    SGAME_HOST: "localhost"
    # The port for the test SGame instance
    SGAME_PORT: "5000"

stages:
    - build
    - test

# Build stage: build the C# SGame executable
build:
    stage: build
    before_script:
        # Before building: restore C# dependencies for SGame
        - "dotnet restore SGame"
    script:
        - "dotnet build SGame"

# Test stage
test:
    stage: test
    script:
        # Run automated tests via pytest.
        # pytest is responsible for launching a test compute node (SGame) to test
        # what it needs to test (and killing it when it's done).
        # See issue #33 for why this is not done through GitLab CI scripts.
        - "cd ${CI_PROJECT_DIR}/tests"
        - "pytest *.py --sgame ${CI_PROJECT_DIR}/SGame" --host ${SGAME_HOST} --port ${SGAME_PORT}
