stages:
    - build
    - test

before_script:
    - "dotnet restore SGame"

build:
    stage: build
    script:
        - "dotnet build SGame"

test:
    stage: test
    script:
        - "cd ${CI_PROJECT_DIR}/tests"
        - "pytest *.py"
