variables:
    # The host the test SGame instance
    SGAME_HOST: "localhost"
    # The port for the test SGame instance
    SGAME_PORT: "5000"

stages:
    - build
    - test

# Before all pipeline stages: restore C# dependencies for SGame
before_script:
    - "dotnet restore SGame"

# Build stage: build the C# SGame executable
build:
    stage: build
    script:
        - "dotnet build SGame"

# Test stage
test:
    stage: test
    script:
        # 1) Start an instance of SGame in the background
        - "dotnet run --project SGame -- --host ${SGAME_HOST} --port ${SGAME_PORT} &"
        # 2) Run automated tests via Pytest
        - "cd ${CI_PROJECT_DIR}/tests"
        - "pytest *.py --host ${SGAME_HOST} --port ${SGAME_PORT}"
        # 3) Kill the background instance of SGame
        - "pkill -KILL $(jobs -p) || echo 'Server already terminated'"
