variables:
    # The host the test SGame instance
    SGAME_HOST: "localhost"
    # The port for the test SGame instance
    SGAME_PORT: "5000"

stages:
    - build
    - test

# Build stage: build the C# SGame executable
build:
    stage: build
    before_script:
        # Before building: restore C# dependencies for SGame
        - "dotnet restore SGame"
    script:
        - "dotnet build SGame"

# Test stage
test:
    stage: test
    script:
        # 0) Tell the GitLab runner to kill any background process when the script runner shell exits.
        #    See: https://gitlab.com/gitlab-org/gitlab-runner/issues/2880
        #    This way the SGame instance will be stopped after the tests are run.
        - "trap 'kill $(jobs -p)' EXIT"
        # 1) Start an instance of SGame in the background
        - "dotnet run --project SGame -- --host ${SGAME_HOST} --port ${SGAME_PORT} &"
        # 2) Run automated tests via Pytest
        - "cd ${CI_PROJECT_DIR}/tests"
        - "pytest *.py --host ${SGAME_HOST} --port ${SGAME_PORT}"
